# Generated by Django 4.2.7 on 2025-09-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
