# Generated by Django 4.2.7 on 2025-09-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentcourse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="studentcourse",
            name="courses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_courses",
                to="api.student",
            ),
        ),
        migrations.RemoveField(
            model_name="studentcourse",
            name="course",
        ),
        migrations.RemoveField(
            model_name="studentcourse",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="studentcourse",
            name="points",
        ),
    ]
