# Generated by Django 4.2.7 on 2025-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_studentcourse_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="has_courses",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
